<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DELL" name="Test4" tests="1" failures="1" timestamp="2 Oct 2020 19:48:06 GMT" time="44.87" errors="0">
  <testcase name="InstaGoogleTest" time="0.052" classname="Instagram.E2EIns.InstaTest4">
    <failure type="java.lang.AssertionError" message="Test Failed">
      <![CDATA[java.lang.AssertionError: Test Failed
	at Instagram.E2EIns.InstaTest4.InstaGoogleTest(InstaTest4.java:36)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- InstaGoogleTest -->
</testsuite> <!-- Test4 -->
